-- AlterTable
ALTER TABLE "User" ADD COLUMN "notifyForumThreads" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifyPolls" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifyProposals" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifyRsvpReminders" BOOLEAN NOT NULL DEFAULT true;
